Feature: add dummy backend API endpoint for extension on slice-finder
zeno-ml/zeno pull request #649
Opened 2023-03-07 00:20 UTC by tianqi-wu

Current version is a dummy version of the backend API endpoint; I plan to start dealing with the slice-finder and relevant APIs this week.

2023-03-07 00:24 UTC, cabreraalex commented
Hmm maybe merge main into both slice-finder-feature and slice-finder-dev?

2023-03-07 17:58 UTC, cabreraalex approved these changes

2023-03-07 17:58 UTC, cabreraalex commented on zeno/backend.py
> +    def slice_finder(self, req):
can you put this in a new file in the folder `processing/` like `processing/slice_finder.py`?

2023-03-07 17:58 UTC, cabreraalex commented on zeno/server.py
> +        return zeno.slice_finder(req)  # TODO: ADD SOMETHING HERE
Related to above, change this to a non-zeno call to a function in the processing folder.

2023-03-07 22:28 UTC, cabreraalex approved these changes
Looks fantastic!

2023-03-29 20:50 UTC, tianqi-wu commented
The current issue lies in the zeno/processing/slice_finder.py file. I tried to get the error rate for each single piece of data, but I am not sure what the syntax should be. @cabreraalex Do you mind looking at it, or make some modifications? Thanks a lot!

2023-04-06 17:40 UTC, cabreraalex commented on zeno/processing/slice_finder.py
> +    # dummy data: error
Instead of this, get one of the columns that is passed from the frontend like:

df[myZenoColumn]

which will be a series w/ numbers.

2023-04-28 14:37 UTC, tianqi-wu commented
This is the checkpoint version before the final version (all pivotal functionalities has achieved with Python 3.9). Here are the features:
1. Allow frontend selection of various numerical data by maximum size, maximum lattice level, metric, and order (ascending/descending). The backend will react accordingly to the prompts/queries, and generate valid result (underperforming slices).
2. Generate slices with correct UI/UX, showing the size and accuracy of slices.
3. The slices generated from the SliceFinder can be added to the main function.
4. Corrected previous UI bugs (associated with z-index and positioning).

Something that may need to be fixed:
1. The current UI version is not final; Erica is still working on the more polished final version of it.
2. My current way of combining backend data with the metric column is to multiply the error value (1,0) of each column with the normalized metric data (blue_border_count, red_count, etc). This is functional and quite efficient, but may not be the best way of handling the issue.

2023-05-05 12:44 UTC, cabreraalex commented on frontend/src/metadata/popups/SliceFinderPopup.svelte
> +	$: start = 0;
Can we get rid of pagination? Just make it hide the overflow and scroll

2023-05-05 12:44 UTC, cabreraalex commented on zeno/processing/slice_finder.py
> +def find_the_right_column(columns, name):
just find_column_name

2023-05-05 12:44 UTC, cabreraalex commented on zeno/processing/slice_finder.py
> +"""
Make this a pydoc by putting it under the function definition

2023-05-05 12:44 UTC, cabreraalex commented on zeno/processing/slice_finder.py
> +    all_df_column_name = updated_df.columns.values
look at the ruff comments for this

2023-05-05 12:44 UTC, cabreraalex commented on zeno/processing/slice_finder.py
> +    updated_df = df.copy(deep=True)
ideally don't do a deep copy, no need and it's expensive

2023-05-05 12:44 UTC, cabreraalex commented on zeno/processing/slice_finder.py
> +    return {
This should be an actual class return type you put in `classes/slice.py`

2023-05-05 12:44 UTC, cabreraalex commented on zeno/__init__.py
> +    SliceFinderMetricReturn,
Why does this have to be in init? I don't think it should.

2023-05-05 12:44 UTC, cabreraalex commented on zeno/api.py
> +        error_rate (float) Error Rate of metric over subset of data
Undo this, we don't need this here.

2023-05-05 12:44 UTC, cabreraalex commented on zeno/api.py
> +class SliceFinderMetricReturn(BaseModel):
Why is this here/what is this? don't think we need this.

2023-05-05 12:44 UTC, cabreraalex commented on zeno/server.py
> +        "/slice-finder-project", tags=["zeno"], response_model=SliceFinderMetricReturn
This return type should be a class in classes/slice_finder.py or something like that.

2023-05-12 13:58 UTC, cabreraalex requested changes
Some comments, but it looks like some of your previous changes were reverted from the previous review

2023-05-12 13:58 UTC, cabreraalex commented on frontend/src/metadata/MetadataPanel.svelte
> +						<path fill="black" d={mdiAssistant} />
Can we use creationOutline here:

import { mdiCreationOutline } from '@mdi/js';

2023-05-12 13:58 UTC, cabreraalex commented on frontend/src/metadata/popups/SliceFinderPopup.svelte
> +	// dummy data for presenting frontend UI
is this still dummy data? 

If not can you comment what these options all are?

2023-05-12 13:58 UTC, cabreraalex commented on frontend/src/metadata/popups/SliceFinderPopup.svelte
> +	let sliceFinderKeys = ["data"];
I think this is wrong. This should list the columns you can pick to do slice finding across.

2023-05-12 13:58 UTC, cabreraalex commented on frontend/src/metadata/popups/SliceFinderPopup.svelte
> +	let sliceFinderKeys = ["data"];
e.g. "brightness", "red count" etc.

2023-05-12 13:58 UTC, cabreraalex requested changes
Some comments, but it looks like some of your previous changes were reverted from the previous review

2023-05-16 03:25 UTC, cabreraalex approved these changes

2023-05-16 03:26 UTC, cabreraalex approved these changes

2023-05-16 03:26 UTC, merged